env: flex
runtime: custom
service: tdl-middleware
automatic_scaling:
  min_num_instances: 1

# !!! Needs to change between projects
beta_settings:
  cloud_sql_instances: computas-universitet:us-east1:tdl-middleware-rails
