secrets:
    - kmsKeyName: projects/cpb100-177720/locations/europe-west1/keyRings/tdl-middleware/cryptoKeys/rails
      secretEnv:
          SECRET_KEY_BASE: CiQA7/gaqQILP5177MeCFqYaTJkitTddpugAyC2c5Ug1ygTmkIYSqgEAvPYZJbjOt2XNAdgw+TrMae4xzPGcB6PwpGeyTevFdsGez3W8BN/mfBxbI+LkJqX7U+440cACcZIlYhz7O/EvnVz8NuWuBDDYZNTz8a0AUKHalghq41kd6ZK0pD+aGQlhI8JmPM0Z47EuR0y/IhCurkH0JJOakU6iEU15UXXgR9oA2grpmTEJoyZ7Hb+9MKJnzwEsXvW8ALZj8ekPIqG/9EirJc5fLcq+PQ==

steps:
    #  Build the Docker image.
    - name: gcr.io/cloud-builders/docker
      args: 
        - build
        - '--build-arg'
        - 'SECRET_KEY_BASE=$$SECRET_KEY_BASE'
        - '--build-arg'
        - JCORU_URL=$_JCORU_URL
        - '--build-arg'
        - MYSQL_USER=$_MYSQL_USER
        - '--build-arg'
        - MYSQL_PASSWORD=$_MYSQL_PASSWORD
        - '--build-arg'
        - MYSQL_SOCKET_PATH=$_MYSQL_SOCKET_PATH
        - '-t'
        - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
        - '.'
      secretEnv: ['SECRET_KEY_BASE']
      
    # Push it to GCR.
    - name: gcr.io/cloud-builders/docker
      args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
      
    # Deploy your Flex app from the image in GCR.
    - name: gcr.io/cloud-builders/gcloud
      args: ['app', 'deploy', 'app.yaml', '--image-url=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

# Note that this build pushes this image.
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
