secrets:
    - kmsKeyName: projects/cpb100-177720/locations/europe-west1/keyRings/tdl-middleware/cryptoKeys/rails
      secretEnv:
          SECRET_KEY_BASE: CiQA0mryFPNe5HHLJPoIApz/WCU2zzzs+YiFHk08dhLZyxZH+CQSqgEAX48QnSNZ1LvnyNTaA6dXJlDyk5btpX4ouggYikBaJthmcwEZ86oZ/NbL6ncmYdihXPRq36J8pJwj2aPaoFXjWz1wljNa8XmJ5y1J0u7Z4iitpbJF59WWicdNPbdHNchSiVVNr3oqVS+1OQj2w+jeuWTYT/ri5gf7RnPa6ceggDCgqdlbqIMKNyrnep1DBFW1oNZDIP+7g8h/ULKpK6aO8kq3xfgzyxUOqA==

steps:
    #  Build the Docker image.
    - name: gcr.io/cloud-builders/docker
      args: 
        - build
        - '--build-arg'
        - 'SECRET_KEY_BASE=$$SECRET_KEY_BASE'
        - '--build-arg'
        - 'JCORU_URL=$_JCORU_URL'
        - '-t'
        - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
        - '.'
      secretEnv: ['SECRET_KEY_BASE']
      
    # Push it to GCR.
    - name: gcr.io/cloud-builders/docker
      args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
      
    # Deploy your Flex app from the image in GCR.
    - name: gcr.io/cloud-builders/gcloud
      args: ['app', 'deploy', 'app.yaml', '--image-url=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

# Note that this build pushes this image.
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
